"""Exam seating PDF generator using ReportLab."""
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
)
from reportlab.lib.enums import TA_CENTER

logger = logging.getLogger(__name__)


def generate_exam_pdf(roll: str, exams: List[Dict[str, Any]]) -> bytes:
    """
    Generate a personalized exam timetable PDF.
    Returns PDF bytes.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20*mm,
        leftMargin=20*mm,
        topMargin=20*mm,
        bottomMargin=20*mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=6,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#1a3c5e"),
    )
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=4,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#2c5f8a"),
    )
    info_style = ParagraphStyle(
        'Info',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=2,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#333333"),
    )
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#888888"),
    )

    elements = []

    # Header
    elements.append(Paragraph("CampusPilot — ClassPilot", title_style))
    elements.append(Paragraph("Personal Exam Timetable", subtitle_style))
    elements.append(Spacer(1, 8))

    # Student info
    elements.append(Paragraph(f"<b>Roll Number:</b> {roll}", info_style))
    elements.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y, %H:%M')}", info_style))
    elements.append(Paragraph(f"<b>Total Exams:</b> {len(exams)}", info_style))
    elements.append(Spacer(1, 12))

    if not exams:
        elements.append(Paragraph("No exams found for this roll number.", info_style))
        doc.build(elements)
        return buffer.getvalue()

    # Table data
    table_data = [
        ["Date", "Day", "Time", "Course", "Room"]
    ]

    for exam in exams:
        raw_date = exam.get("exam_date") or exam.get("date")
        exam_date = raw_date
        if isinstance(exam_date, str):
            try:
                exam_date = datetime.strptime(exam_date, "%Y-%m-%d").date()
            except ValueError:
                exam_date = None

        start = exam.get("start_time") or ""
        end = exam.get("end_time") or ""
        time_str = f"{start} - {end}" if start or end else "-"

        table_data.append([
            exam_date.strftime("%d %b %Y") if exam_date else "-",
            exam_date.strftime("%A") if exam_date else "-",
            time_str,
            exam.get("course_code") or "-",
            exam.get("room") or "-",
        ])

    # Create table
    col_widths = [35*mm, 25*mm, 40*mm, 55*mm, 30*mm]
    table = Table(table_data, colWidths=col_widths, repeatRows=1)

    table_style = TableStyle([
        # Header
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1a3c5e")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        
        # Body
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('ALIGN', (0, 1), (2, -1), 'CENTER'),
        ('ALIGN', (3, 1), (3, -1), 'LEFT'),
        ('ALIGN', (4, 1), (4, -1), 'CENTER'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f8fc")]),
        
        # Padding
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ])
    table.setStyle(table_style)
    elements.append(table)

    elements.append(Spacer(1, 20))

    # Footer
    elements.append(Paragraph(
        f"Generated by CampusPilot ClassPilot on {datetime.now().strftime('%d %B %Y at %H:%M')}",
        footer_style
    ))
    elements.append(Paragraph(
        "Please verify exam details with official university timetable.",
        footer_style
    ))

    doc.build(elements)
    return buffer.getvalue()


def save_exam_pdf(roll: str, exams: List[Dict[str, Any]], output_dir: Path) -> Path:
    """Generate and save PDF to file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    filename = f"exam_timetable_{roll}_{datetime.now().strftime('%Y%m%d')}.pdf"
    filepath = output_dir / filename
    
    pdf_bytes = generate_exam_pdf(roll, exams)
    filepath.write_bytes(pdf_bytes)
    logger.info(f"Exam PDF saved: {filepath}")
    return filepath