"""Infrastructure layer for monitoring feature."""

from features.monitoring.infrastructure.collector import (
    validate_event,
    user_hash,
    ip_hash,
    collect,
    CollectError,
    COLLECT_BATCH_LIMIT,
    CRASH_LIMIT,
    ALLOWED_EVENTS,
    MAX_PROPS,
    MAX_PROP_LEN,
    MAX_MESSAGE,
)
from features.monitoring.infrastructure.metrics import (
    REGISTRY,
    REQUESTS,
    REQUEST_DURATION,
    REQUEST_IN_FLIGHT,
    DB_QUERY_DURATION,
    DB_QUERIES,
    COLLECTOR_EVENTS,
    SCAN_DURATION,
    SCAN_RUNS,
    SCAN_FAILURES,
    LATENCY_BUCKETS,
    route_template,
    status_class,
)
from features.monitoring.infrastructure.ratelimit import (
    SlidingWindowLimiter,
    COLLECT_BATCH_LIMIT as _COLLECT_BATCH_LIMIT,
    CRASH_LIMIT as _CRASH_LIMIT,
    AUTH_LIMIT,
    BRUTE_FORCE_LIMIT,
    OTP_RESEND_LIMIT,
)
from features.monitoring.infrastructure.rollup import (
    rollup,
    prune,
    _hour_bucket_expr,
    _aggregate_stmt,
    _coalesce_dim,
)

__all__ = [
    "ALLOWED_EVENTS",
    "AUTH_LIMIT",
    "BRUTE_FORCE_LIMIT",
    "COLLECTOR_EVENTS",
    "COLLECT_BATCH_LIMIT",
    "CRASH_LIMIT",
    "DB_QUERIES",
    "DB_QUERY_DURATION",
    "LATENCY_BUCKETS",
    "MAX_MESSAGE",
    "MAX_PROPS",
    "MAX_PROP_LEN",
    "OTP_RESEND_LIMIT",
    "REGISTRY",
    "REQUESTS",
    "REQUEST_DURATION",
    "REQUEST_IN_FLIGHT",
    "SCAN_DURATION",
    "SCAN_FAILURES",
    "SCAN_RUNS",
    "CollectError",
    "SlidingWindowLimiter",
    "_aggregate_stmt",
    "_coalesce_dim",
    "_hour_bucket_expr",
    "collect",
    "ip_hash",
    "prune",
    "rollup",
    "route_template",
    "status_class",
    "user_hash",
    "validate_event",
]