"""monitoring_events_and_scans

Revision ID: 27f44ac2c78b
Revises: 0001
Create Date: 2026-10-07 15:23:42.164698
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '27f44ac2c78b'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ad_network', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ad_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revenue_micros', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_event_ad_network'), 'ad_event', ['ad_network'], unique=False)
    op.create_index(op.f('ix_ad_event_ad_unit'), 'ad_event', ['ad_unit'], unique=False)
    op.create_index(op.f('ix_ad_event_app_version'), 'ad_event', ['app_version'], unique=False)
    op.create_index(op.f('ix_ad_event_event_type'), 'ad_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_ad_event_platform'), 'ad_event', ['platform'], unique=False)
    op.create_index(op.f('ix_ad_event_ts'), 'ad_event', ['ts'], unique=False)
    op.create_index(op.f('ix_ad_event_user_hash'), 'ad_event', ['user_hash'], unique=False)
    op.create_table('crash_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exception_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('fatal', sa.Boolean(), nullable=False),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('foreground', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crash_report_app_version'), 'crash_report', ['app_version'], unique=False)
    op.create_index(op.f('ix_crash_report_device_model'), 'crash_report', ['device_model'], unique=False)
    op.create_index(op.f('ix_crash_report_exception_type'), 'crash_report', ['exception_type'], unique=False)
    op.create_index(op.f('ix_crash_report_fatal'), 'crash_report', ['fatal'], unique=False)
    op.create_index(op.f('ix_crash_report_fingerprint'), 'crash_report', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_crash_report_foreground'), 'crash_report', ['foreground'], unique=False)
    op.create_index(op.f('ix_crash_report_kind'), 'crash_report', ['kind'], unique=False)
    op.create_index(op.f('ix_crash_report_os_version'), 'crash_report', ['os_version'], unique=False)
    op.create_index(op.f('ix_crash_report_platform'), 'crash_report', ['platform'], unique=False)
    op.create_index(op.f('ix_crash_report_session_id'), 'crash_report', ['session_id'], unique=False)
    op.create_index(op.f('ix_crash_report_ts'), 'crash_report', ['ts'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('props', sa.JSON(), nullable=False),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_app_version'), 'event', ['app_version'], unique=False)
    op.create_index(op.f('ix_event_country'), 'event', ['country'], unique=False)
    op.create_index(op.f('ix_event_device_model'), 'event', ['device_model'], unique=False)
    op.create_index(op.f('ix_event_event_name'), 'event', ['event_name'], unique=False)
    op.create_index(op.f('ix_event_os_version'), 'event', ['os_version'], unique=False)
    op.create_index(op.f('ix_event_platform'), 'event', ['platform'], unique=False)
    op.create_index(op.f('ix_event_session_id'), 'event', ['session_id'], unique=False)
    op.create_index(op.f('ix_event_ts'), 'event', ['ts'], unique=False)
    op.create_index(op.f('ix_event_user_hash'), 'event', ['user_hash'], unique=False)
    op.create_table('event_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_hour', sa.DateTime(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_hour', 'platform', 'event_name', 'app_version', 'os_version', 'country', name='uq_event_hourly')
    )
    op.create_index(op.f('ix_event_hourly_app_version'), 'event_hourly', ['app_version'], unique=False)
    op.create_index(op.f('ix_event_hourly_bucket_hour'), 'event_hourly', ['bucket_hour'], unique=False)
    op.create_index(op.f('ix_event_hourly_country'), 'event_hourly', ['country'], unique=False)
    op.create_index(op.f('ix_event_hourly_event_name'), 'event_hourly', ['event_name'], unique=False)
    op.create_index(op.f('ix_event_hourly_os_version'), 'event_hourly', ['os_version'], unique=False)
    op.create_index(op.f('ix_event_hourly_platform'), 'event_hourly', ['platform'], unique=False)
    op.create_table('monitoring_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_session_app_version'), 'monitoring_session', ['app_version'], unique=False)
    op.create_index(op.f('ix_monitoring_session_country'), 'monitoring_session', ['country'], unique=False)
    op.create_index(op.f('ix_monitoring_session_device_model'), 'monitoring_session', ['device_model'], unique=False)
    op.create_index(op.f('ix_monitoring_session_os_version'), 'monitoring_session', ['os_version'], unique=False)
    op.create_index(op.f('ix_monitoring_session_platform'), 'monitoring_session', ['platform'], unique=False)
    op.create_index(op.f('ix_monitoring_session_session_id'), 'monitoring_session', ['session_id'], unique=False)
    op.create_index(op.f('ix_monitoring_session_started_at'), 'monitoring_session', ['started_at'], unique=False)
    op.create_index(op.f('ix_monitoring_session_user_hash'), 'monitoring_session', ['user_hash'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_micros', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_app_version'), 'purchase', ['app_version'], unique=False)
    op.create_index(op.f('ix_purchase_platform'), 'purchase', ['platform'], unique=False)
    op.create_index(op.f('ix_purchase_product_id'), 'purchase', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_transaction_id'), 'purchase', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_purchase_ts'), 'purchase', ['ts'], unique=False)
    op.create_index(op.f('ix_purchase_user_hash'), 'purchase', ['user_hash'], unique=False)
    op.create_index(op.f('ix_purchase_verified'), 'purchase', ['verified'], unique=False)
    op.create_table('scan_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subsection', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('root_causes', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', name='uq_scan_result_id')
    )
    op.create_index(op.f('ix_scan_result_created_at'), 'scan_result', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_result_model'), 'scan_result', ['model'], unique=False)
    op.create_index(op.f('ix_scan_result_scan_id'), 'scan_result', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scan_result_status'), 'scan_result', ['status'], unique=False)
    op.create_index(op.f('ix_scan_result_subsection'), 'scan_result', ['subsection'], unique=False)
    op.create_table('security_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_event_app_version'), 'security_event', ['app_version'], unique=False)
    op.create_index(op.f('ix_security_event_blocked'), 'security_event', ['blocked'], unique=False)
    op.create_index(op.f('ix_security_event_ip_hash'), 'security_event', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_security_event_kind'), 'security_event', ['kind'], unique=False)
    op.create_index(op.f('ix_security_event_platform'), 'security_event', ['platform'], unique=False)
    op.create_index(op.f('ix_security_event_ts'), 'security_event', ['ts'], unique=False)
    op.create_index(op.f('ix_security_event_user_hash'), 'security_event', ['user_hash'], unique=False)
    op.create_table('status_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsection', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_transition_at'), 'status_transition', ['at'], unique=False)
    op.create_index(op.f('ix_status_transition_from_status'), 'status_transition', ['from_status'], unique=False)
    op.create_index(op.f('ix_status_transition_scan_id'), 'status_transition', ['scan_id'], unique=False)
    op.create_index(op.f('ix_status_transition_subsection'), 'status_transition', ['subsection'], unique=False)
    op.create_index(op.f('ix_status_transition_to_status'), 'status_transition', ['to_status'], unique=False)
    op.create_table('tool_call_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('metric_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_audit_metric_key'), 'tool_call_audit', ['metric_key'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_ok'), 'tool_call_audit', ['ok'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_scan_id'), 'tool_call_audit', ['scan_id'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_tool'), 'tool_call_audit', ['tool'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_call_audit_tool'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_scan_id'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_ok'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_metric_key'), table_name='tool_call_audit')
    op.drop_table('tool_call_audit')
    op.drop_index(op.f('ix_status_transition_to_status'), table_name='status_transition')
    op.drop_index(op.f('ix_status_transition_subsection'), table_name='status_transition')
    op.drop_index(op.f('ix_status_transition_scan_id'), table_name='status_transition')
    op.drop_index(op.f('ix_status_transition_from_status'), table_name='status_transition')
    op.drop_index(op.f('ix_status_transition_at'), table_name='status_transition')
    op.drop_table('status_transition')
    op.drop_index(op.f('ix_security_event_user_hash'), table_name='security_event')
    op.drop_index(op.f('ix_security_event_ts'), table_name='security_event')
    op.drop_index(op.f('ix_security_event_platform'), table_name='security_event')
    op.drop_index(op.f('ix_security_event_kind'), table_name='security_event')
    op.drop_index(op.f('ix_security_event_ip_hash'), table_name='security_event')
    op.drop_index(op.f('ix_security_event_blocked'), table_name='security_event')
    op.drop_index(op.f('ix_security_event_app_version'), table_name='security_event')
    op.drop_table('security_event')
    op.drop_index(op.f('ix_scan_result_subsection'), table_name='scan_result')
    op.drop_index(op.f('ix_scan_result_status'), table_name='scan_result')
    op.drop_index(op.f('ix_scan_result_scan_id'), table_name='scan_result')
    op.drop_index(op.f('ix_scan_result_model'), table_name='scan_result')
    op.drop_index(op.f('ix_scan_result_created_at'), table_name='scan_result')
    op.drop_table('scan_result')
    op.drop_index(op.f('ix_purchase_verified'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_user_hash'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_ts'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_transaction_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_product_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_platform'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_app_version'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_monitoring_session_user_hash'), table_name='monitoring_session')
    op.drop_index(op.f('ix_monitoring_session_started_at'), table_name='monitoring_session')
    op.drop_index(op.f('ix_monitoring_session_session_id'), table_name='monitoring_session')
    op.drop_index(op.f('ix_monitoring_session_platform'), table_name='monitoring_session')
    op.drop_index(op.f('ix_monitoring_session_os_version'), table_name='monitoring_session')
    op.drop_index(op.f('ix_monitoring_session_device_model'), table_name='monitoring_session')
    op.drop_index(op.f('ix_monitoring_session_country'), table_name='monitoring_session')
    op.drop_index(op.f('ix_monitoring_session_app_version'), table_name='monitoring_session')
    op.drop_table('monitoring_session')
    op.drop_index(op.f('ix_event_hourly_platform'), table_name='event_hourly')
    op.drop_index(op.f('ix_event_hourly_os_version'), table_name='event_hourly')
    op.drop_index(op.f('ix_event_hourly_event_name'), table_name='event_hourly')
    op.drop_index(op.f('ix_event_hourly_country'), table_name='event_hourly')
    op.drop_index(op.f('ix_event_hourly_bucket_hour'), table_name='event_hourly')
    op.drop_index(op.f('ix_event_hourly_app_version'), table_name='event_hourly')
    op.drop_table('event_hourly')
    op.drop_index(op.f('ix_event_user_hash'), table_name='event')
    op.drop_index(op.f('ix_event_ts'), table_name='event')
    op.drop_index(op.f('ix_event_session_id'), table_name='event')
    op.drop_index(op.f('ix_event_platform'), table_name='event')
    op.drop_index(op.f('ix_event_os_version'), table_name='event')
    op.drop_index(op.f('ix_event_event_name'), table_name='event')
    op.drop_index(op.f('ix_event_device_model'), table_name='event')
    op.drop_index(op.f('ix_event_country'), table_name='event')
    op.drop_index(op.f('ix_event_app_version'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_crash_report_ts'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_session_id'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_platform'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_os_version'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_kind'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_foreground'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_fingerprint'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_fatal'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_exception_type'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_device_model'), table_name='crash_report')
    op.drop_index(op.f('ix_crash_report_app_version'), table_name='crash_report')
    op.drop_table('crash_report')
    op.drop_index(op.f('ix_ad_event_user_hash'), table_name='ad_event')
    op.drop_index(op.f('ix_ad_event_ts'), table_name='ad_event')
    op.drop_index(op.f('ix_ad_event_platform'), table_name='ad_event')
    op.drop_index(op.f('ix_ad_event_event_type'), table_name='ad_event')
    op.drop_index(op.f('ix_ad_event_app_version'), table_name='ad_event')
    op.drop_index(op.f('ix_ad_event_ad_unit'), table_name='ad_event')
    op.drop_index(op.f('ix_ad_event_ad_network'), table_name='ad_event')
    op.drop_table('ad_event')
    # ### end Alembic commands ###