"""initial schema from SQLModel metadata

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 14:05:05.313044
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=False),
    sa.Column('is_extra', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_code'), 'course', ['code'], unique=True)
    op.create_table('exam_seating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_start_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roll_start_num', sa.Integer(), nullable=False),
    sa.Column('roll_end_num', sa.Integer(), nullable=False),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seating_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('is_extra', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_seating_branch'), 'exam_seating', ['branch'], unique=False)
    op.create_index(op.f('ix_exam_seating_course_code'), 'exam_seating', ['course_code'], unique=False)
    op.create_index(op.f('ix_exam_seating_is_extra'), 'exam_seating', ['is_extra'], unique=False)
    op.create_index(op.f('ix_exam_seating_roll_end_num'), 'exam_seating', ['roll_end_num'], unique=False)
    op.create_index(op.f('ix_exam_seating_roll_start_num'), 'exam_seating', ['roll_start_num'], unique=False)
    op.create_index(op.f('ix_exam_seating_roll_start_prefix'), 'exam_seating', ['roll_start_prefix'], unique=False)
    op.create_index(op.f('ix_exam_seating_semester'), 'exam_seating', ['semester'], unique=False)
    op.create_table('exam_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_upload_kind'), 'exam_upload', ['kind'], unique=False)
    op.create_table('feed_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uidvalidity', sa.Integer(), nullable=True),
    sa.Column('last_uid', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_cursor_mailbox'), 'feed_cursor', ['mailbox'], unique=True)
    op.create_table('mid_sem_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mid_sem_schedule_branch'), 'mid_sem_schedule', ['branch'], unique=False)
    op.create_index(op.f('ix_mid_sem_schedule_course_code'), 'mid_sem_schedule', ['course_code'], unique=False)
    op.create_index(op.f('ix_mid_sem_schedule_semester'), 'mid_sem_schedule', ['semester'], unique=False)
    op.create_table('pending_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_signup_email'), 'pending_signup', ['email'], unique=True)
    op.create_table('timetable_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instructor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch_or_program', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_slot_course_code'), 'timetable_slot', ['course_code'], unique=False)
    op.create_index(op.f('ix_timetable_slot_day'), 'timetable_slot', ['day'], unique=False)
    op.create_table('timetable_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roll_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_roll_number'), 'user', ['roll_number'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('attendance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'CANCELLED', name='attendancestatus'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_record_course_id'), 'attendance_record', ['course_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachment_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachment_original', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('hackathon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('poster_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('feed_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathon_created_by'), 'hackathon', ['created_by'], unique=False)
    op.create_index(op.f('ix_hackathon_feed_uid'), 'hackathon', ['feed_uid'], unique=False)
    op.create_index(op.f('ix_hackathon_is_active'), 'hackathon', ['is_active'], unique=False)
    op.create_index(op.f('ix_hackathon_is_featured'), 'hackathon', ['is_featured'], unique=False)
    op.create_index(op.f('ix_hackathon_source'), 'hackathon', ['source'], unique=False)
    op.create_index(op.f('ix_hackathon_title'), 'hackathon', ['title'], unique=False)
    op.create_table('passkey_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passkey_challenge_challenge'), 'passkey_challenge', ['challenge'], unique=True)
    op.create_index(op.f('ix_passkey_challenge_user_id'), 'passkey_challenge', ['user_id'], unique=False)
    op.create_table('passkey_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.JSON(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passkey_credential_credential_id'), 'passkey_credential', ['credential_id'], unique=True)
    op.create_index(op.f('ix_passkey_credential_user_id'), 'passkey_credential', ['user_id'], unique=False)
    op.create_table('password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_code_code_hash'), 'password_reset_code', ['code_hash'], unique=False)
    op.create_index(op.f('ix_password_reset_code_user_id'), 'password_reset_code', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('programme', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('elective_codes', sa.JSON(), nullable=True),
    sa.Column('attendance_target', sa.Float(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch_changed_at', sa.DateTime(), nullable=True),
    sa.Column('branch_change_requested', sa.Boolean(), nullable=False),
    sa.Column('requested_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch_change_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch_change_requested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.create_table('feedback_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_reply_feedback_id'), 'feedback_reply', ['feedback_id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('wanted', sa.JSON(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('request_to_join', sa.Boolean(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('hackathon_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathon.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_hackathon_id'), 'team', ['hackathon_id'], unique=False)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=True)
    op.create_index(op.f('ix_team_owner_id'), 'team', ['owner_id'], unique=False)
    op.create_table('join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_request_status'), 'join_request', ['status'], unique=False)
    op.create_index(op.f('ix_join_request_team_id'), 'join_request', ['team_id'], unique=False)
    op.create_index(op.f('ix_join_request_user_id'), 'join_request', ['user_id'], unique=False)
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    op.create_index(op.f('ix_team_member_team_id'), 'team_member', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_member_user_id'), 'team_member', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE (hand-written addition): autogenerate drops the attendance_record
    # table but NOT the `attendancestatus` enum type it depends on. Postgres
    # keeps named enum types as schema objects, so a downgrade followed by an
    # upgrade fails with:
    #
    #     psycopg.errors.DuplicateObject: type "attendancestatus" already exists
    #
    # That makes downgrade unusable and, worse, makes it look like the upgrade
    # is broken. Dropping the type explicitly - after the table that uses it, and
    # with checkfirst so it is a no-op on a partially-torn-down database - makes
    # the upgrade/downgrade cycle round-trip cleanly.
    #
    # Verified by: alembic downgrade base && alembic upgrade head
    op.drop_index(op.f('ix_team_member_user_id'), table_name='team_member')
    op.drop_index(op.f('ix_team_member_team_id'), table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_join_request_user_id'), table_name='join_request')
    op.drop_index(op.f('ix_join_request_team_id'), table_name='join_request')
    op.drop_index(op.f('ix_join_request_status'), table_name='join_request')
    op.drop_table('join_request')
    op.drop_index(op.f('ix_team_owner_id'), table_name='team')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_hackathon_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_feedback_reply_feedback_id'), table_name='feedback_reply')
    op.drop_table('feedback_reply')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_password_reset_code_user_id'), table_name='password_reset_code')
    op.drop_index(op.f('ix_password_reset_code_code_hash'), table_name='password_reset_code')
    op.drop_table('password_reset_code')
    op.drop_index(op.f('ix_passkey_credential_user_id'), table_name='passkey_credential')
    op.drop_index(op.f('ix_passkey_credential_credential_id'), table_name='passkey_credential')
    op.drop_table('passkey_credential')
    op.drop_index(op.f('ix_passkey_challenge_user_id'), table_name='passkey_challenge')
    op.drop_index(op.f('ix_passkey_challenge_challenge'), table_name='passkey_challenge')
    op.drop_table('passkey_challenge')
    op.drop_index(op.f('ix_hackathon_title'), table_name='hackathon')
    op.drop_index(op.f('ix_hackathon_source'), table_name='hackathon')
    op.drop_index(op.f('ix_hackathon_is_featured'), table_name='hackathon')
    op.drop_index(op.f('ix_hackathon_is_active'), table_name='hackathon')
    op.drop_index(op.f('ix_hackathon_feed_uid'), table_name='hackathon')
    op.drop_index(op.f('ix_hackathon_created_by'), table_name='hackathon')
    op.drop_table('hackathon')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_attendance_record_course_id'), table_name='attendance_record')
    op.drop_table('attendance_record')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_roll_number'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('timetable_upload')
    op.drop_index(op.f('ix_timetable_slot_day'), table_name='timetable_slot')
    op.drop_index(op.f('ix_timetable_slot_course_code'), table_name='timetable_slot')
    op.drop_table('timetable_slot')
    op.drop_index(op.f('ix_pending_signup_email'), table_name='pending_signup')
    op.drop_table('pending_signup')
    op.drop_index(op.f('ix_mid_sem_schedule_semester'), table_name='mid_sem_schedule')
    op.drop_index(op.f('ix_mid_sem_schedule_course_code'), table_name='mid_sem_schedule')
    op.drop_index(op.f('ix_mid_sem_schedule_branch'), table_name='mid_sem_schedule')
    op.drop_table('mid_sem_schedule')
    op.drop_index(op.f('ix_feed_cursor_mailbox'), table_name='feed_cursor')
    op.drop_table('feed_cursor')
    op.drop_index(op.f('ix_exam_upload_kind'), table_name='exam_upload')
    op.drop_table('exam_upload')
    op.drop_index(op.f('ix_exam_seating_semester'), table_name='exam_seating')
    op.drop_index(op.f('ix_exam_seating_roll_start_prefix'), table_name='exam_seating')
    op.drop_index(op.f('ix_exam_seating_roll_start_num'), table_name='exam_seating')
    op.drop_index(op.f('ix_exam_seating_roll_end_num'), table_name='exam_seating')
    op.drop_index(op.f('ix_exam_seating_is_extra'), table_name='exam_seating')
    op.drop_index(op.f('ix_exam_seating_course_code'), table_name='exam_seating')
    op.drop_index(op.f('ix_exam_seating_branch'), table_name='exam_seating')
    op.drop_table('exam_seating')
    op.drop_index(op.f('ix_course_code'), table_name='course')
    op.drop_table('course')
    # The enum type outlives its table unless removed explicitly - see the note
    # at the top of downgrade().
    sa.Enum(name='attendancestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###